### ISSUE TITLE
Cannot Build alfresco-metadata-writer with Maven

### ISSUE THREAD

**Issue by toby-cyberity** [Redpill-Linpro/alfresco-metadata-writer#6]
I have not been able to build the meta-data-writer using mvn install.
I have pasted the error below:

C:\Program Files\Maven\alfresco-metadata-writer-develop>"C:\Program Files\Maven\
apache-maven-3.3.1\bin\mvn" install
[INFO] Scanning for projects...
Downloading: https://maven.redpill-linpro.com/nexus/content/groups/public/com/re
dpill-linpro/alfresco/alfresco-base/2.0.0/alfresco-base-2.0.0.pom
Downloaded: https://maven.redpill-linpro.com/nexus/content/groups/public/com/red
pill-linpro/alfresco/alfresco-base/2.0.0/alfresco-base-2.0.0.pom (35 KB at 8.9 K
B/sec)
Downloading: https://maven.redpill-linpro.com/nexus/content/groups/public/org/al
fresco/maven/alfresco-sdk-parent/2.0.0/alfresco-sdk-parent-2.0.0.pom
Downloaded: https://maven.redpill-linpro.com/nexus/content/groups/public/org/alf
resco/maven/alfresco-sdk-parent/2.0.0/alfresco-sdk-parent-2.0.0.pom (40 KB at 93
.8 KB/sec)
Downloading: https://maven.redpill-linpro.com/nexus/content/groups/public/org/al
fresco/maven/alfresco-sdk-aggregator/2.0.0/alfresco-sdk-aggregator-2.0.0.pom
Downloaded: https://maven.redpill-linpro.com/nexus/content/groups/public/org/alf
resco/maven/alfresco-sdk-aggregator/2.0.0/alfresco-sdk-aggregator-2.0.0.pom (13
KB at 73.4 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find org.alfresco:alfresco-platfor
m-distribution:pom:4.2.4 in https://maven.redpill-linpro.com/nexus/content/group
s/public was cached in the local repository, resolution will not be reattempted
until the update interval of redpill-public has elapsed or updates are forced @
line 26, column 19
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.redpill-linpro.alfresco.module:metadatawriter:4.2.6 (C
:\Program Files\Maven\alfresco-metadata-writer-develop\pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Failure to find org.alfresco:alfresco-pla
tform-distribution:pom:4.2.4 in https://maven.redpill-linpro.com/nexus/content/g
roups/public was cached in the local repository, resolution will not be reattemp
ted until the update interval of redpill-public has elapsed or updates are force
d @ line 26, column 19 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

I have tried editing the pom.xml and changing the alfresco-base pom and this has not worked.
I have tried alfresco-base-2.0.0.pom and alfresco-base-1.1.1.7.pom.
Do you have a working version of this Maven Project?

Thanks

**Comment by oakman** [comment]
Hi,

The metadata writer builds against Alfresco Enterprise 4.2.4. Alfresco has locked those artifacts behind a login, so you have to configure Maven a bit in order for it to build against that version. You have to update the version in the pom to build it against the community version instead, for example 4.2.d.

/Niklas

**Comment by toby-cyberity** [comment]
Morning,

I have amended pom.xml to build from Alfresco Version 4.2.d however I am still getting errors after the build nearly completes.
Could this be that some of the files you are using are refering to the Enterprise Release so I am not able to resolve them?
It seems it cant download the files listed below up to this point it can download the files.
Errors are below.

Downloading: https://repo.maven.apache.org/maven2/org/alfresco/alfresco-platform
-distribution/4.2.2/alfresco-platform-distribution-4.2.2.pom
Downloading: http://maven.redpill-linpro.com/nexus/content/groups/public/org/alf
resco/alfresco-platform-distribution/4.2.2/alfresco-platform-distribution-4.2.2.
pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfr
esco/alfresco-platform-distribution/4.2.2/alfresco-platform-distribution-4.2.2.p
om
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshot
s/org/alfresco/alfresco-platform-distribution/4.2.2/alfresco-platform-distributi
on-4.2.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.374 s
[INFO] Finished at: 2015-03-27T09:53:38+00:00
[INFO] Final Memory: 18M/149M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project metadatawriter: Could not resolve depe
ndencies for project org.redpill-linpro.alfresco.module:metadatawriter:jar:4.2.6
: Failed to collect dependencies at org.redpill-linpro.alfresco:alfresco-test-re
po:jar:1.0.4: Failed to read artifact descriptor for org.redpill-linpro.alfresco
:alfresco-test-repo:jar:1.0.4: Could not find artifact org.alfresco:alfresco-pla
tform-distribution:pom:4.2.2 in redpill-public (https://maven.redpill-linpro.com
/nexus/content/groups/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

Many Thanks
Toby

**Comment by toby-cyberity** [comment]
Good Afternoon,

Do you have an update on the above please.
We are very keen to use this functionality with our Alfresco 5.0 instance.

Many Thanks
Toby

**Comment by marsv024** [comment]
Hi,

Try the branch feature/community_50: https://github.com/Redpill-Linpro/alfresco-metadata-writer/tree/feature/community_50

See if that works.

/Marcus

**Comment by toby-cyberity** [comment]
Afternoon,

I have just tried and it fails toward the end with the following:

Downloaded: http://maven.redpill-linpro.com/nexus/content/groups/public/org/jvne
t/staxex/stax-ex/maven-metadata.xml (769 B at 0.3 KB/sec)
Downloading: https://maven.redpill-linpro.com/nexus/content/groups/public/org/al
fresco/alfresco-platform-distribution/4.2.2/alfresco-platform-distribution-4.2.2
.pom
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/alfresco-platform
-distribution/4.2.2/alfresco-platform-distribution-4.2.2.pom
Downloading: http://maven.redpill-linpro.com/nexus/content/groups/public/org/alf
resco/alfresco-platform-distribution/4.2.2/alfresco-platform-distribution-4.2.2.
pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfr
esco/alfresco-platform-distribution/4.2.2/alfresco-platform-distribution-4.2.2.p
om
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshot
s/org/alfresco/alfresco-platform-distribution/4.2.2/alfresco-platform-distributi
on-4.2.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:44 min
[INFO] Finished at: 2015-04-20T15:27:50+01:00
[INFO] Final Memory: 16M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project metadatawriter: Could not resolve depe
ndencies for project org.redpill-linpro.alfresco.module:metadatawriter:jar:5.0.0
-SNAPSHOT: Failed to collect dependencies at org.redpill-linpro.alfresco:alfresc
o-test-repo:jar:1.0.4: Failed to read artifact descriptor for org.redpill-linpro
.alfresco:alfresco-test-repo:jar:1.0.4: Could not find artifact org.alfresco:alf
resco-platform-distribution:pom:4.2.2 in redpill-public (https://maven.redpill-l
inpro.com/nexus/content/groups/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

Looks to me like it is trying to download dependency's from the Alfresco 4.2.2 repository and does not have access.

Any ideas?

Many Thanks
Toby

**Comment by carande** [comment]
Hello,

I am in a similar situation to Toby above, except that I am trying to build with maven against Alfresco Community 4.2.e.

I get the exact same result (the second error posted in this thread) after editing the alfresco.version property in the POM and running mvn package.  I'm using the master branch version.

I also noticed this message early in the maven process, perhaps it is related? 

[WARNING] Failed to build parent project for org.redpill-linpro.alfresco.module:metadatawriter:jar:4.2.6

**Comment by carande** [comment]
Also, when building this project, is the overall directory structure important?  Specifically, does this project need to be build in a certain location relative to my alfresco install, or perhaps I need to specify the path to my alfresco install somewhere?  Or is the .jar created independently of any existing alfresco process?

**Comment by toby-cyberity** [comment]
Afternoon,

Could someone please come back to us with a way forward.
I am very keen to use the Metadata-writer but cant build the project at the moment.

Thanks
Toby

**Comment by oakman** [comment]
I'm looking at this now, sorry for the delay.

/N

**Comment by marsv024** [comment]
Perhaps we should look into changing all the base-projects / open source projects to use the community version instead of the enterprise if they are not using enterprise specific. After all the API calls should be the same for the whole 4.2.x branch for instance.

/M

**Comment by oakman** [comment]
This should be fixed now, Toby, can you try to build?

**Comment by toby-cyberity** [comment]
Afternoon,

I have been able to build the project against the latest 4 version thanks very much for fixing the issues.
Will this version work with Alfresco V 5.0?
Could you now make it so I can build the Alfresco V 5.0 version of the Alfresco-Metadata-Writer.
Hope this is possible.

Many Thanks
Toby

**Comment by toby-cyberity** [comment]
Afternoon,

Do you have a wiki or some documentation for install/configuration instructions for the Alfresco-Metadata-Writer?

Thanks
Toby

**Comment by oakman** [comment]
I'm closing this and adding separate tickets for 5.0 and wiki docs.

**Comment by carande** [comment]
Thanks, fixed for me as well!
